server:
  port: 9091

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: root

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UserDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update