server:
  port: 9092
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic
        ssl:
          enabled: true
          trust-store: classpath:truststore.jks
          trust-store-password: password
          trust-store-type: JKS
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: root

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HRDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
